services:

  tracker:
    build: ./src/tracker/.
    ports:
      - '3000:3000'
    environment:
      MYSQL_HOST: tracker-db
      MYSQL_USER: root
      MYSQL_PASSWORD: ''
      MYSQL_DB: tracker
    networks:
      - tracker-network
    depends_on:
      - tracker-db

  tracker-db:
    build: ./src/db/.
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'tracker'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    networks:
      - tracker-network

networks:
  tracker-network:
    driver: bridge

version: '3.9'